/**
 * Payload and request types for tiers T0–T2, generated by hand from
 * `sdk/endpoint-inventory.json` (`payloadTypes`) and checked against the controllers it was
 * generated from.
 *
 * Two rules run through the whole file and are worth stating once rather than repeating on ninety
 * properties:
 *
 * **Optional means optional.** Nulls are omitted on write, and a missing field means null or the
 * type's default (CONTRACT §2), so a decoder that required a field would fail on a legal frame.
 * A property is non-optional here only when the *endpoint* rejects the request without it — which
 * is a stricter and more useful test than the C# nullability the inventory records: a C# `bool` or
 * `long` is non-nullable and still perfectly absent on the wire.
 *
 * **`long` is `number`, except for message ids, which are `string` — and that exception is the
 * whole of what follows.** Never `bigint`: `JSON.parse` cannot produce one, so a `bigint` field
 * would be a lie the first time a frame was decoded. `number` is exact to 2^53, and every seq and
 * unix-ms timestamp this platform issues does stay well inside it.
 *
 * **✅ Fixed on 2026-08-28; the account below is kept because the reasoning is still load-bearing.**
 * Every message-id field in this file is `string`, the server writes them as strings on both
 * surfaces, and a guardrail (`MessageIdWireFormatTests`) fails the server build if any of them ever
 * serialises as a number again. Nothing here needs working around any more. What follows is *why*
 * the type is `string` — read it before you decide it looks over-cautious and change it back.
 * 2026-08-28 已修复，下文保留是因为它的推理仍然有用：本文件里每一个消息 id 字段都是 string，
 * 服务端两个面都按字符串下发，并且有一条护栏在它们哪天又变回数字时让服务端构建变红。
 * 已经没有需要绕开的东西了；下面讲的是**为什么**是 string——在你觉得它多余、想改回去之前先读它。
 *
 * **`messageId` does not fit in a double.** Measured against a live server on 2026-08-25: the server issued
 * `350598345233801216`, about 2^58 — thirty-eight times past the safe limit. Calling
 * `msg.recall` with the value a JS client sends back returns 1400 `message not found`; the
 * same call with the exact id succeeds.
 *
 * **The mechanism is not what it first looks like, and the difference matters.** Doubles near
 * 2^58 are spaced 64 apart. That particular id has zero sequence bits, so it is a multiple of
 * 4096 and `JSON.parse` reproduces it *exactly* — `BigInt(parsed)` is the original. What is
 * lossy is the way back out: JavaScript prints a number as the shortest decimal that
 * round-trips to the same double, and for this value that shortest decimal is
 * `350598345233801200` — a different integer. So `JSON.stringify` sends the server an id it
 * never issued. An id minted with non-zero sequence bits is not a multiple of 64 at all and
 * is rounded on the way *in* instead (…223 arrives as …216).
 *
 * Either way a JavaScript client cannot round-trip a message id, which is why re-reading the
 * raw text on receive is not a sufficient fix: the value has to leave as a string too.
 * **这个机制和它初看的样子不一样**：2^58 附近相邻 double 相距 64，而该 id 序列位为 0、
 * 是 4096 的倍数，所以 JSON.parse 得到的是**精确值**；丢失发生在**回程**——
 * JS 打印数字用「能往返到同一个 double 的最短十进制」，于是写出 …200 这个**另一个整数**。
 * 序列位非 0 的 id 则在**来路**就被舍入。两种情形都无法完整往返。
 *
 * **It is not a future risk; it has been true since 2024-01-25.** The snowflake epoch is
 * 2024-01-01 and the timestamp is shifted left 22 bits, so an id stays under 2^53 only for the
 * first 24.86 days after that epoch. Every message id minted after 2024-01-25T20:31:23Z is
 * unsafe here, and the margin only grows.
 *
 * **Affected fields**: `messageId`, `quoteMessageId`, `threadRootId` and the `messageIds` array
 * on translation — all of them message ids, so quoted replies and threads are affected too.
 * `seq`, `minSeq`, `maxSeq` and `readSeq` are per-conversation counters and are safe.
 * 不是"将来会溢出"：epoch 是 2024-01-01、时间戳左移 22 位，安全窗口只有 24.86 天，
 * **2024-01-25 之后铸出的每一个消息 id 都不安全**。受影响的是全部消息 id 字段
 * （含 quoteMessageId / threadRootId / messageIds），seq 一族是会话内计数器、安全。
 * Every call that hands a messageId back was affected: recall, edit, delete, read receipts,
 * quoted replies, and translation's `messageIds`. Reading the raw text on receive was never a
 * sufficient fix on its own — the value has to leave as a string too, which is what makes the
 * field type, and not a parser tweak, the actual repair.
 *
 * The sentence that used to stand here said all three id kinds stayed well inside 2^53. It was
 * wrong about messageId, and it is left retracted rather than deleted because anyone who read
 * it and sized a field on it needs to find it again. The inconsistency it describes — `groupId` a
 * string, `messageId` a number, inside one protocol — was tracked as B-9 and is closed: message ids
 * are strings everywhere now, on all five SDKs and on both server surfaces.
 * 上面那句「messageId 稳稳在 2^53 以内」是**假的**：实测约 2^58，超出 38 倍，
 * JSON.parse 会静默取整，用取整后的值撤回会得到 1400，用精确值则成功。
 * groupId 是字符串、没有问题——**同一份协议里两种做法**，这才是真正的缺陷。
 *
 * 可选就是可选：服务端写 JSON 时省略 null，缺字段即默认值。只有端点会因为缺它而拒绝请求的字段
 * 才是必填——这比照搬 C# 可空性更有用，C# 的 bool/long 不可空，但在线上完全可以不出现。
 */

import type {
  AgentStatus,
  ApplicationStatus,
  ConversationType,
  DeskCannedReplyScope,
  DeskDisposition,
  DeskEndReason,
  DeskNoteKind,
  DeskSessionState,
  GroupInviteMode,
  GroupJoinMode,
  GroupRole,
  GroupType,
  KbArticleState,
  MessageContentType,
  MessagePriority,
  MessageStatus,
  MultiLoginPolicy,
  MuteMode,
  Platform,
} from './protocol.js';

/**
 * `content` and `extensions` are per-`contentType` and tenant-extensible, so they stay untyped
 * JSON. Inventing a model for `content` would be wrong for the tenant that adds a field to it the
 * day after the SDK ships (CONTRACT §4.5).
 */
export type JsonObject = Record<string, unknown>;

// ---------------------------------------------------------------------------- conn (T0)

export interface HeartbeatResult {
  serverTime: number;
  /** How often to beat, in seconds. The server owns this cadence; the SDK adopts whatever it says. */
  intervalSeconds: number;
  /** True when this beat rebuilt a routing entry the cluster had lost. Worth logging, never acting on. */
  healed: boolean;
  /** This socket's cluster-unique id. Put it in a support ticket and the connection is findable. */
  connectionId: string;
  nodeId: string;
}

export interface ReauthRequest {
  token: string;
}

export interface ResumeRequest {
  /**
   * Highest **committed** seq per conversation — the seq the application has durably stored, not
   * the highest it has been handed. Reporting the latter is the data-loss bug in CONTRACT §5.1.
   */
  convSeqs?: Record<string, number>;
  /** Newest `ConversationView.updatedAt` fully consumed, unix ms. */
  conversationCursor?: number;
  cursor?: string | null;
  /** Server clamps to 1…500; anything outside becomes 200. */
  limit?: number;
}

export interface ResumeResult {
  conversations: ConversationView[];
  nextCursor?: string | null;
  hasMore: boolean;
  /** conversationId → first seq the client is missing. Feed each into `msg.sync`. */
  gapsFrom: Record<string, number>;
  serverTime: number;
}

// ---------------------------------------------------------------------------- messages

export interface RecallInfo {
  operatorId: string;
  recallTime: number;
  byAdmin: boolean;
  reason?: string | null;
}

export interface EditInfo {
  operatorId: string;
  editTime: number;
  version: number;
}

export interface PushConfig {
  title?: string | null;
  body?: string | null;
  sound?: string | null;
  payload?: Record<string, string> | null;
  badgeCount?: boolean;
  channelId?: string | null;
}

export interface MessageOptions {
  persistent?: boolean;
  updateConversation?: boolean;
  countUnread?: boolean;
  offlinePush?: boolean;
  pushConfig?: PushConfig | null;
  needReceipt?: boolean;
  priority?: MessagePriority;
  /** Online-only messages carry `seq: 0` and never touch a cursor. */
  onlineOnly?: boolean;
  noSelfSync?: boolean;
  expireIn?: number | null;
  moderationBypass?: boolean;
}

export interface ImMessage {
  appId: string;
  conversationId: string;
  conversationType: ConversationType;
  /**
   * Gap-free position inside the conversation. Ordering, dedupe and gap repair all key off this.
   * `0` means the message was never persisted (typing, presence, chat-room traffic).
   */
  seq: number;
  messageId: string;
  clientMsgId: string;
  senderId: string;
  senderPlatform: Platform;
  contentType: MessageContentType;
  content: JsonObject;
  searchText?: string | null;
  mentionAll?: boolean;
  mentionedUserIds?: string[];
  quoteMessageId?: string | null;
  threadRootId?: string | null;
  options?: MessageOptions;
  status?: MessageStatus;
  recalled?: RecallInfo | null;
  edited?: EditInfo | null;
  reactions?: Record<string, string[]> | null;
  deletedForUsers?: string[] | null;
  sendTime: number;
  /** Authoritative server clock, unix ms. */
  createTime: number;
  expireAt?: number | null;
  extensions?: JsonObject | null;
}

export interface MessageBrief {
  messageId: string;
  seq: number;
  senderId: string;
  contentType: MessageContentType;
  digest: string;
  createTime: number;
  recalled: boolean;
}

export interface SendMessageRequest {
  /** One of `conversationId`, `receiverId` or `groupId`. The server resolves the other two. */
  conversationId?: string;
  receiverId?: string;
  groupId?: string;
  conversationType?: ConversationType;
  /**
   * Idempotency key. Optional here because the SDK generates one when it is absent — which is what
   * makes a blind retry safe for a caller who never thought about it.
   */
  clientMsgId?: string;
  /** Defaults to `MessageContentType.Text`. */
  contentType?: MessageContentType;
  content: JsonObject;
  mentionAll?: boolean;
  mentionedUserIds?: string[];
  quoteMessageId?: string;
  threadRootId?: string;
  options?: MessageOptions;
  /** Client clock, unix ms. The SDK fills it in; the server does not trust it for ordering. */
  sendTime?: number;
  extensions?: JsonObject;
}

export interface SendMessageResult {
  messageId: string;
  seq: number;
  conversationId: string;
  clientMsgId: string;
  createTime: number;
  /** True when the server matched an earlier send on `clientMsgId` and returned the original result. */
  deduplicated?: boolean;
  contentModified?: boolean;
}

export interface SyncMessagesRequest {
  conversationId: string;
  fromSeq?: number;
  /** 0 means "up to the conversation's maxSeq". */
  toSeq?: number;
  /** Server clamps to 500. A wider window is more iterations of the repair loop, not a bigger call. */
  limit?: number;
  ascending?: boolean;
}

export interface SyncMessagesResult {
  conversationId: string;
  messages: ImMessage[];
  maxSeq: number;
  /** Lowest seq this user may read — a cleared history or a late group join raises it. */
  minSeq: number;
  /**
   * Computed on the raw window, **before** per-user hidden messages are filtered out. So
   * `messages` can be shorter than `limit` — even empty — while this is true. Loop on this, never
   * on `messages.length` (CONTRACT §5.9).
   */
  hasMore: boolean;
}

export interface HistoryRequest {
  conversationId: string;
  /** Exclusive: the oldest seq you already hold. Omit for the newest page. */
  beforeSeq?: number;
  /** Server clamps to 200; defaults to 20. */
  limit?: number;
}

export interface RecallMessageRequest {
  conversationId: string;
  messageId: string;
  reason?: string;
}

export interface DeleteMessagesRequest {
  conversationId: string;
  messageIds: string[];
  /** Deleting for everyone needs the permission the server checks; it is not a client capability by default. */
  forEveryone?: boolean;
}

export interface EditMessageRequest {
  conversationId: string;
  messageId: string;
  content: JsonObject;
}

export interface ForwardMessagesRequest {
  sourceConversationId: string;
  messageIds: string[];
  targetConversationIds: string[];
  /** True bundles them into one merged message rather than forwarding each. */
  merge?: boolean;
  mergeTitle?: string;
  clientMsgId?: string;
}

export interface ReactRequest {
  conversationId: string;
  messageId: string;
  emoji: string;
  /** False removes the caller's reaction. Defaults to true. */
  add?: boolean;
}

export interface ReceiptRequest {
  conversationId: string;
  messageIds: string[];
}

export interface TypingRequest {
  conversationId: string;
  typing?: boolean;
}

// ---------------------------------------------------------------------------- conversations

export interface ConversationSetting {
  pinned?: boolean;
  muted?: MuteMode;
  draft?: string;
  tags?: string[];
  extensions?: JsonObject;
}

export interface ConversationView {
  conversationId: string;
  type: ConversationType;
  lastMessage?: MessageBrief | null;
  maxSeq: number;
  readSeq: number;
  unreadCount: number;
  pinned: boolean;
  muted: MuteMode;
  draft?: string | null;
  tags?: string[] | null;
  manuallyUnread?: boolean;
  /** Sort key of the conversation list and the input to `conversationCursor`. Unix ms. */
  updatedAt: number;
  /** Present for single conversations when the server can resolve the peer cheaply. */
  peer?: UserProfile | null;
  group?: Group | null;
  extensions?: JsonObject | null;
}

export interface ListConversationsRequest {
  /** Only conversations changed after this unix-ms timestamp. 0 means all. */
  updatedAfter?: number;
  cursor?: string | null;
  /** Server clamps to 200; defaults to 50. */
  limit?: number;
}

export interface ConversationIdRequest {
  conversationId: string;
}

export interface ReadRequest {
  conversationId: string;
  readSeq: number;
}

export interface UpdateConversationSettingRequest {
  conversationId: string;
  setting?: ConversationSetting;
}

// ---------------------------------------------------------------------------- users

export interface UserProfile {
  appId: string;
  userId: string;
  nickname?: string | null;
  avatar?: string | null;
  gender?: number;
  birthday?: string | null;
  signature?: string | null;
  /** Hashed server-side; the plaintext never reaches a client. */
  phoneHash?: string | null;
  emailHash?: string | null;
  silencedUntil?: number | null;
  banned?: boolean;
  multiLoginOverride?: MultiLoginPolicy | null;
  createdAt: number;
  updatedAt: number;
  extensions?: JsonObject | null;
}

export interface UserIdRequest {
  userId: string;
}

export interface UserIdsRequest {
  /** At most 200 per request; the server refuses more rather than truncating silently. */
  userIds: string[];
}

export interface UpdateProfileRequest {
  /**
   * Sparse patch. `appId`, `userId`, `banned`, `silencedUntil`, `createdAt` and
   * `multiLoginOverride` are stripped server-side whatever the client sends — a client must never
   * be able to unban itself.
   */
  patch: JsonObject;
}

export interface PresenceState {
  userId: string;
  online: boolean;
  platforms: Platform[];
  lastSeen: number;
  customStatus?: string | null;
}

export interface SubscribePresenceRequest {
  userIds: string[];
  /**
   * Subscriptions expire rather than living until an unsubscribe, because a client that crashes
   * never sends one. 1…3600; anything outside becomes 600.
   */
  ttlSeconds?: number;
}

// ---------------------------------------------------------------------------- friends

export interface Friend {
  appId: string;
  userId: string;
  friendUserId: string;
  remark?: string | null;
  tags?: string[] | null;
  source?: string | null;
  addTime: number;
  extensions?: JsonObject | null;
}

export interface FriendRequest {
  appId: string;
  fromUserId: string;
  toUserId: string;
  greeting?: string | null;
  source?: string | null;
  status: ApplicationStatus;
  handleReason?: string | null;
  createdAt: number;
  handledAt?: number | null;
}

export interface BlockEntry {
  appId: string;
  userId: string;
  blockedUserId: string;
  createdAt: number;
  reason?: string | null;
}

export interface CursorRequest {
  cursor?: string | null;
  /** 1…200; anything outside becomes 50. */
  limit?: number;
}

export interface AddFriendRequest {
  userId: string;
  greeting?: string;
  source?: string;
}

export interface HandleFriendRequest {
  fromUserId: string;
  accept: boolean;
  reason?: string;
}

export interface FriendRequestListRequest {
  /** True lists requests sent to me; false lists requests I sent. Defaults to true. */
  incoming?: boolean;
  cursor?: string | null;
  limit?: number;
}

export interface BlockRequest {
  userId: string;
  reason?: string;
}

// ---------------------------------------------------------------------------- groups

export interface Group {
  appId: string;
  groupId: string;
  type: GroupType;
  name: string;
  avatar?: string | null;
  introduction?: string | null;
  announcement?: string | null;
  announcementUpdatedAt?: number | null;
  ownerId: string;
  memberCount: number;
  maxMemberCount: number;
  joinMode: GroupJoinMode;
  inviteMode: GroupInviteMode;
  muteAll: boolean;
  muteEndTime?: number | null;
  dismissed: boolean;
  createdAt: number;
  updatedAt: number;
  extensions?: JsonObject | null;
}

export interface GroupMember {
  appId: string;
  groupId: string;
  userId: string;
  role: GroupRole;
  nickname?: string | null;
  muteEndTime?: number | null;
  joinTime: number;
  joinSource?: string | null;
  extensions?: JsonObject | null;
}

export interface CreateGroupRequest {
  /** Leave empty and the server allocates one. */
  groupId?: string;
  name: string;
  avatar?: string;
  introduction?: string;
  type?: GroupType;
  /** The caller is added and made owner whatever this says. */
  memberIds?: string[];
  joinMode?: GroupJoinMode;
  inviteMode?: GroupInviteMode;
  maxMemberCount?: number;
  extensions?: JsonObject;
}

export interface GroupIdRequest {
  groupId: string;
}

export interface UpdateGroupRequest {
  name?: string;
  avatar?: string;
  introduction?: string;
  joinMode?: GroupJoinMode;
  inviteMode?: GroupInviteMode;
  maxMemberCount?: number;
  extensions?: JsonObject;
}

export interface UpdateGroupCommand {
  groupId: string;
  update?: UpdateGroupRequest;
}

export interface GroupCursorRequest {
  groupId: string;
  cursor?: string | null;
  /** 1…100; anything outside becomes 50. A super group is never listed in one frame. */
  limit?: number;
}

export interface GroupMembersRequest {
  groupId: string;
  userIds: string[];
  reason?: string;
}

export interface JoinGroupRequest {
  groupId: string;
  reason?: string;
}

// ---------------------------------------------------------------------------- media

export interface UploadTicketRequest {
  fileName: string;
  /** MIME type. The server refuses types the tenant has not allowed rather than accepting the upload. */
  contentType: string;
  size?: number;
}

export interface MediaUploadTicket {
  /**
   * Put **this** in the message, never `downloadUrl`. Every reader signs their own short-lived
   * link from the key, which is what makes expiry and revocation possible at all — a URL baked
   * into a message is public forever the moment it leaks.
   */
  objectKey: string;
  /** Presigned PUT. Upload goes straight to object storage, never through the gateway. */
  uploadUrl: string;
  downloadUrl: string;
  /** Present when the storage backend needs a multipart POST rather than a PUT. */
  formFields?: Record<string, string> | null;
  expiresAt: number;
}

export interface DownloadUrlRequest {
  objectKey: string;
  /** 1…86400; anything outside becomes 3600. */
  lifetimeSeconds?: number;
}

// ---------------------------------------------------------------------------- push

/**
 * Vendor channel. Aliases (`ios`, `firebase`, `hms`, …) are folded server-side; an unknown value is
 * **rejected** with the legal list rather than stored as a token nothing can route.
 *
 * Empty falls back to the platform default, which is only reliable on iOS — Android fragments
 * across five OEM channels and the server cannot guess which one a token came from (CONTRACT §6.1).
 */
export type PushProvider = 'apns' | 'fcm' | 'huawei' | 'xiaomi' | 'oppo' | 'vivo' | 'honor' | (string & {});

export interface RegisterPushTokenRequest {
  provider: PushProvider;
  token: string;
  /** BCP-47. Defaults to the socket's `lang`. */
  language?: string;
}

/**
 * Body of `push.clicked` — the tap on a notification, reported back for the delivery funnel.
 *
 * **Both fields are optional and the identity is never in the body.** The row is located from the
 * connection: a `pushId` is only believed when it points at this user's own device, and without one
 * the server takes this device's newest delivery. That is what stops a client from marking another
 * user's notification clicked, or probing which `pushId` values exist.
 *
 * `messageId` is a **string** for the reason every message id in this SDK is one: the ids exceed
 * JavaScript's exact-integer range, and a number round-trips to a different id.
 */
export interface PushClickedRequest {
  /** The delivery's `pu_…` id, when the notification payload carried one. */
  pushId?: string;
  /** The payload's `msgId`, when the tap gave you one. */
  messageId?: string;
}

// ---------------------------------------------------------------------------- moderation

/**
 * Why a report was filed. The server's vocabulary, not a hint: an unrecognised value is **rejected**
 * (`1001`, "that is not a report category") rather than folded into `other`, which would quietly
 * change what the reporter said. Unlike {@link PushProvider}, the refusal does not name the legal
 * values — take them from this union, not from the error message.
 *
 * Left open the way {@link PushProvider} is. A category the platform adds should be reachable the
 * day it ships, and a closed union would turn that into a compile error on the customer's machine
 * — which is a decision about their release schedule, not ours.
 */
export type ReportCategory =
  | 'spam'
  | 'harassment'
  | 'fraud'
  | 'pornography'
  | 'violence'
  | 'other'
  | (string & {});

/**
 * An end user reporting another.
 *
 * **There is no field for the reporter and there must not be.** It comes from the socket, which is
 * the only surface where the user id is a fact rather than a parameter; a field would let one
 * account file in another's name, which is both a way to get somebody banned and a way to poison
 * the count a moderator decides on.
 *
 * 举报人来自连接，请求体里没有这个字段：有了它，一个账号就能以另一个账号的名义举报。
 */
export interface SubmitReportRequest {
  /** Who is being reported. Reporting yourself is refused `1001`. */
  targetUserId: string;
  /** Where it happened. Optional: a report can be about an account rather than a place. */
  conversationId?: string;
  /**
   * The message being reported. **Omit it to report the account rather than one message.**
   *
   * A string, like every message id in this SDK and for the same reason — snowflake ids run past
   * JavaScript's safe-integer range, so a number cannot survive the round trip. The note at the top
   * of this file has the measurement.
   */
  messageId?: string;
  /** Defaults to `other` server-side, so a reporting UI without a picker still files something. */
  category?: ReportCategory;
  /** What the reporter typed. Usually the most useful field on the row a moderator ends up reading. */
  note?: string;
}

/**
 * A receipt, not the row.
 *
 * The reporter has no business reading back the moderation state of their own report, and the row
 * carries fields — who handled it, what they did — that are internal. Two fields is the whole
 * answer: enough to say "filed at 14:03, reference rp_…" in the UI and in a support conversation.
 */
export interface ReportReceipt {
  /** `rp_…`. Quote it when a customer asks what happened to a specific report. */
  reportId: string;
  /** Server clock, unix ms. */
  createdAt: number;
}
// ---------------------------------------------------------------------------- desk (T4)

/**
 * A customer asking for a person. **Every field is optional and the body may be omitted entirely** —
 * the server reads `null` as an empty request — so the plain "talk to a human" button is
 * `im.desk.request()`.
 *
 * Idempotent by the server's design, not by the caller's discipline: a customer who already has a
 * session in flight — queued, assigned, or still with the bot — gets that same session back rather
 * than a second one. The client most likely to call this twice is the one whose first call timed
 * out after it had already succeeded.
 * 幂等由服务端保证：最可能重复调用的，正是「超时但其实已经成功」的那个客户端。
 */
export interface DeskRequest {
  /** Routing hint the tenant queues on: product line, language, VIP tier. */
  skill?: string;
  /** Higher goes first. Used sparingly — a queue where everything is urgent has no order. */
  priority?: number;
  /**
   * Opaque context the agent's workbench renders: order id, the page they were on, a prior ticket.
   *
   * The engine copies out the keys it recognises ({@link DeskContextKeys}) and leaves everything
   * else here untouched, so a tenant's own keys travel to the workbench without a schema change.
   */
  context?: JsonObject;
}

/** One "customer asked, agent answered" pair inside a session, unix ms on both sides. */
export interface DeskResponseSample {
  customerAt: number;
  agentAt: number;
  /** Who answered, so a per-agent response time can be built from the same rows. */
  agentId?: string | null;
}

/**
 * The model-written handover summary a receiving agent reads before saying hello.
 *
 * All five members are always present when the summary itself is — a session with no summary has
 * `summary` absent rather than an empty card. `model` is here because a summary is a claim and
 * claims carry authorship.
 */
export interface DeskSessionSummary {
  /** What the customer came about. */
  issue: string;
  /** Where the conversation stands. */
  state: string;
  /** What the next agent should do first. */
  nextStep: string;
  generatedAt: number;
  /** Which provider and model wrote it. */
  model: string;
}

/**
 * One desk session, as `desk.request`, `desk.accept` and every session-level `evt.desk` frame
 * return it.
 *
 * **The last thirteen fields are the customer-service product's and were added after the engine
 * shipped** (SPEC-06 §14.1, §13.2), so a session opened before they existed has no element for any
 * of them and reads back as the default: absent, `[]`, or `false`. A build of the server that
 * predates them omits them altogether. They are therefore optional here even though a current
 * server writes `tags: []`, `ratingTags: []`, `responseSamples: []` and `star: false` out — the
 * type has to describe both servers, and `?? []` at the edge is the whole of the difference.
 *
 * 最后十三个字段是产品后加的：更早开出的会话根本没有这些元素，读回来就是默认值。
 * 所以它们在这里是可选的——尽管当前服务端会把空数组和 false 写出来，类型要同时描述两种服务端。
 */
export interface DeskSession {
  sessionId: string;
  appId: string;
  /** The IM user asking for help. A minted visitor's id is `v_…`; see {@link DeskSession.visitorId}. */
  customerId: string;
  /** The agent holding it. Absent while queued, and absent again after a release. */
  agentId?: string | null;
  /**
   * The ordinary single chat between the customer and the desk account. Everything either side
   * says is a normal message in it, sent with `msg.send` — these fields only move the *assignment*
   * around that conversation.
   */
  conversationId: string;
  state: DeskSessionState;
  skill?: string | null;
  priority: number;
  /** Unix ms. Preserved across a requeue, which is what keeps a transferred customer's place. */
  queuedAt: number;
  assignedAt?: number | null;
  closedAt?: number | null;
  /** Free-text outcome the closing agent typed. Predates the structured {@link DeskSession.disposition}. */
  resolution?: string | null;
  context?: JsonObject | null;
  /** Agents who held it before, so a transfer chain is auditable. `[]` on a session nobody has held. */
  history?: string[];
  /** When the first agent message reached the customer, unix ms. Absent while no agent has spoken. */
  firstAgentMessageAt?: number | null;
  /** 1–5, absent until (and unless) the customer rates. */
  rating?: number | null;
  /**
   * When the 1807 invitation actually went out, unix ms.
   *
   * **This is the CSAT participation denominator** (SPEC-06 §10.1), and it is stored rather than
   * derived because every reason an invitation was withheld expires long before a report runs.
   * Counting closed sessions instead prices the rate against a denominator several times too
   * large and draws a healthy desk as an ignored one.
   * 这是参评率的分母，且是存下来的而不是推导的：拿「已关闭会话」当分母会把一个健康的客服台画成没人理。
   */
  ratingInvitedAt?: number | null;
  ratingComment?: string | null;
  ratedAt?: number | null;
  summary?: DeskSessionSummary | null;

  // ---- the customer-service product's fields ------------------------------------------------

  /** Labels the closing agent chose. Two-level paths as the centre configured them. */
  tags?: string[];
  /** How the visitor arrived: `web`, `app`, `api`, and the WeChat kinds. */
  channel?: string | null;
  /** The product's visitor record behind {@link DeskSession.customerId}, when the customer is a minted visitor. */
  visitorId?: string | null;
  /** The centre this session belongs to. Absent for a session opened before centres existed. */
  deskId?: string | null;
  /** The skill group it was routed to — the product's id for what the engine routes on as `skill`. */
  groupId?: string | null;
  disposition?: DeskDisposition | null;
  /** Why it ended. A **string** on the wire, unlike `state`. Absent while it is open. */
  endReason?: DeskEndReason | null;
  /** The 1–2 star tags joined — the "why" behind a bad score. Absent for a good or untagged one. */
  ratingReason?: string | null;
  /** The customer's answer to "was your problem solved". Absent until rated, and absent when the survey did not ask. */
  ratingResolved?: boolean | null;
  /** Every per-star tag the customer picked, whatever the score. */
  ratingTags?: string[];
  /** Starred by the holding agent for their own list. */
  star?: boolean;
  /** Unix ms until which the session is snoozed. */
  snoozedUntil?: number | null;
  /** One sample per customer message that got a reply, for the average response time. */
  responseSamples?: DeskResponseSample[];
}

/**
 * Which session to take. **Omit the id — and the whole body — to take the next one waiting**, which
 * is the normal case: agents pull, nothing is ever pushed at them. Naming an id is a supervisor or
 * an agent picking a specific customer out of the queue.
 *
 * An empty queue answers `1002 NotFound`, not an empty success.
 */
export interface DeskAcceptRequest {
  sessionId?: string;
}

/** What both halves of a transfer carry, whichever of the three targets is named. */
export interface DeskTransferBase {
  sessionId: string;
  /**
   * Handover note for the receiving agent. **Internal**: it is filed as a note and never enters the
   * customer-visible 1803 line, so it can say what an agent would not say to the customer.
   */
  note?: string;
}

/**
 * Hands a session on, carrying its whole history with it (SPEC-06 §4.4).
 *
 * **Exactly one of the three targets, enforced by the type rather than by a round trip.** The
 * server checks the same thing and answers `1001 "exactly one of toAgentId, toSkill or toQueue is
 * required"`; expressing it as a union means a workbench that names two — or none — does not
 * compile, instead of failing in front of a customer mid-handover. That is also why the two
 * unusable members are `never` in each branch rather than merely absent: an object literal built by
 * spreading a form's state would otherwise satisfy the branch it half-matches.
 *
 * The cost is real and worth naming: a `toQueue: boolean` held in a variable does not type-check,
 * because "maybe the queue" is not a target. Branch at the call site, which is where the agent's
 * three radio buttons already branch.
 *
 * 三个目标里恰好一个，由类型而不是由一次往返来保证：多写一个或一个不写都编译不过，
 * 而不是在交接到一半时当着客户的面失败。代价是不能用一个 boolean 变量表达 toQueue——
 * 「也许是队列」不是一个目标。
 */
export type DeskTransferRequest =
  | (DeskTransferBase & {
      /** A named agent, who must be available and under capacity. */
      toAgentId: string;
      toSkill?: never;
      toQueue?: false;
    })
  | (DeskTransferBase & {
      /** A skill queue; the session goes to the front of it with its original `queuedAt` stamp. */
      toSkill: string;
      toAgentId?: never;
      toQueue?: false;
    })
  | (DeskTransferBase & {
      /** Back to the queue it came from, same stamp, same position — the 1805 requeue, chosen by a person. */
      toQueue: true;
      toAgentId?: never;
      toSkill?: never;
    });

/**
 * The end-of-session drawer (SPEC-06 §4.9). Every field but the id is optional, and **an omitted
 * field is not the same as a field set to null**: the server writes nulls out of its own JSON, so
 * it reads "absent" as "the agent did not fill this in".
 *
 * **`inviteRating` omitted means `true`.** It is a C# property initialiser, not a nullable, so the
 * only way to close without asking for a rating is to send `inviteRating: false` explicitly.
 * Passing `undefined` still invites.
 * 省略 inviteRating 等于 true：只有显式发 false 才是「不邀评」。
 */
export interface DeskCloseRequest {
  sessionId: string;
  /** Free-text outcome, kept on the record for whoever reads it later. */
  resolution?: string;
  /** At most 20, each at most 64 characters; over either and the whole call is `1001`. */
  tags?: string[];
  disposition?: DeskDisposition;
  /** The agent-edited summary, filed as a note. Never shown to the customer. */
  summary?: string;
  /** Defaults to true when absent. The engine's own anti-noise rules still apply on top. */
  inviteRating?: boolean;
}

/**
 * Availability, and — by the same call — the heartbeat that proves this workbench is still there.
 *
 * The two are one message on purpose: an agent listed as available whose console stopped talking to
 * the server is exactly the state that leaves a customer waiting on somebody who went home, so
 * there is no way to express it.
 */
export interface DeskStatusRequest {
  /** A number on the wire. Anything outside 0–3 is `1001 "unknown agent status '<n>'"`. */
  status: AgentStatus;
  /** Sessions this agent will hold at once. Absent keeps the deployment default; the server clamps it. */
  maxConcurrent?: number;
}

/**
 * The customer's answer to the rating survey (SPEC-06 §4.9), sent in reply to the 1807 notice.
 *
 * Absent is meaningful on all three optional members and is not the same as a falsy value:
 * `resolved` absent means the survey did not ask, and an absent `starTags` is "no tags offered"
 * rather than "none picked".
 */
export interface DeskRateRequest {
  sessionId: string;
  /** 1–5. Anything else is `1001`. */
  score: number;
  /** "Was your problem solved" — the only customer-side evidence of first-contact resolution. */
  resolved?: boolean;
  /** At most 12, each at most 64 characters. With a 1–2 star score these are the reason behind it. */
  starTags?: string[];
  /** At most 2000 characters. */
  comment?: string;
}

/** Body of `desk.suggest`: the session this agent holds. */
export interface DeskSuggestRequest {
  sessionId: string;
}

/**
 * Which canned replies to list. All three are filters; omitting all three lists the whole centre's
 * phrasebook, **including every member's `personal` entries** — see `ownerMemberId`.
 */
export interface DeskCannedRequest {
  skill?: string;
  /** One tier only. An unrecognised value is `1001`. */
  scope?: DeskCannedReplyScope;
  /**
   * Whose personal entries to include. **A filter, not a guard: the server does not narrow this to
   * the caller.** Absent means "do not filter by owner", which returns everyone's `personal`
   * entries, and a value belonging to somebody else returns theirs. Pass your own member id to get
   * "shared, plus mine". Only `/console/v1/desks/{deskId}/canned-replies` rewrites the owner to
   * the caller.
   * 过滤参数而非权限：服务端不按调用方收窄，省略即返回所有人的 personal 条目。
   */
  ownerMemberId?: string;
}

/** One canned reply an agent pastes instead of retyping the same answer. At most 200 per tenant. */
export interface DeskCannedReply {
  /** Store-assigned; empty string on create. */
  id: string;
  /** At most 100 characters. */
  title: string;
  /** At most 4000 characters. */
  content: string;
  /** Absent means every agent sees it. */
  skill?: string | null;
  /** Never absent: an entry stored before the field existed reads back as `all`. */
  scope: DeskCannedReplyScope;
  /** The folder the workbench files it under. Absent is the root. */
  folder?: string | null;
  /** Required for a `personal` entry — without it the write is `1001`. Absent for the other two tiers. */
  ownerMemberId?: string | null;
  updatedAt: number;
}

/** The queue as a supervisor watches it. */
export interface DeskQueueView {
  waiting: number;
  assigned: number;
  availableAgents: number;
  /** Seconds the head of the queue has been waiting — the number a supervisor actually watches. */
  headWaitSeconds: number;
  /**
   * Average seconds from entering the queue to the first agent message, over the last 24 hours.
   *
   * **Absent means "nothing measurable in the window", and a dashboard must draw it that way.**
   * Drawing a 0 says "instant answers", which is the opposite of what an empty window means.
   * 缺席表示「窗口内没有可测样本」，要画成「暂无数据」——画 0 就成了「秒回」。
   */
  avgFirstResponseSeconds?: number | null;
  waitingBySkill: Record<string, number>;
}

/**
 * One agent as the roster sees them right now.
 *
 * A console that has stopped heart-beating is still listed: `lastSeenAt` is what makes it stale,
 * and hiding the row would hide the fact that somebody's workbench died holding sessions.
 */
export interface DeskAgentView {
  agentId: string;
  status: AgentStatus;
  /** Declared capacity: how many concurrent sessions this agent accepts. */
  maxConcurrent: number;
  /** Counted from the live set, never a stored counter. */
  activeSessions: number;
  /** Last heartbeat, unix ms. Stale with a non-offline status means they dropped without saying goodbye. */
  lastSeenAt: number;
}

/**
 * One waiting visitor's place in the line, from the widget surface (SPEC-06 §14.3).
 *
 * **`position` and `minutes` are both "not measured" when absent, never zero.** A session that is
 * no longer queued answers with both absent and `queued: false`, which is how a plugin knows to
 * stop asking rather than to render a 0.
 */
export interface DeskQueuePosition {
  sessionId: string;
  queued: boolean;
  /** 1-based place in its own skill queue. */
  position?: number | null;
  /** A rough wait, present only when there is something real to derive it from. */
  minutes?: number | null;
  /** How long this visitor has already waited, seconds. Always measurable. */
  waitedSeconds: number;
}

/** One knowledge-base article. The embedding never leaves the server. */
export interface KbArticle {
  /** Store-assigned; empty string on create. */
  id: string;
  /** At most 200 characters. */
  title: string;
  /** At most 20000 characters. */
  body: string;
  /** At most 20. `[]` rather than absent on an article this build wrote. */
  tags?: string[];
  /**
   * **Read-only, and the server computes it**: `vector` when the stored embedding matches the
   * tenant's current provider and model, `keyword` otherwise — including when no LLM is configured
   * at all. Sending a value here does not change it; it is rendered so a tenant can see which
   * articles need re-embedding after switching models.
   */
  retrieval?: string;
  /** The help-centre category. Absent is uncategorised. */
  category?: string | null;
  /** A draft is kept but grounds nothing. An article stored before the field existed reads as published. */
  state?: KbArticleState;
  /** Other phrasings of the question this answers: at most 20, each at most 200 characters. */
  similarQuestions?: string[];
  /** Pinned to the top of the help centre and the widget's first screen. */
  featured?: boolean;
  updatedAt: number;
}

/** Who wrote a note, as the frame announcing it carries them. */
export interface DeskNoteAuthor {
  memberId: string;
  name?: string | null;
  avatar?: string | null;
}

/**
 * One internal note on a session: an agent's remark, a handover text, the model's summary, or a
 * supervisor's whisper. **None of it is ever shown to the customer.**
 */
export interface DeskNote {
  noteId: string;
  deskId: string;
  appId: string;
  sessionId: string;
  /** The transcript it belongs to, when known — lets a timeline join without a second read. */
  conversationId?: string | null;
  /** The member who wrote it. Absent for a note the engine or the model authored. */
  authorMemberId?: string | null;
  kind: DeskNoteKind;
  body: string;
  /** Members addressed with `@`. Each is told, and the workbench's "@me" group counts them. */
  mentions?: string[];
  /** Unix ms. */
  at: number;
}
