/**
 * Payload and request types for tiers T0–T2, generated by hand from
 * `sdk/endpoint-inventory.json` (`payloadTypes`) and checked against the controllers it was
 * generated from.
 *
 * Two rules run through the whole file and are worth stating once rather than repeating on ninety
 * properties:
 *
 * **Optional means optional.** Nulls are omitted on write, and a missing field means null or the
 * type's default (CONTRACT §2), so a decoder that required a field would fail on a legal frame.
 * A property is non-optional here only when the *endpoint* rejects the request without it — which
 * is a stricter and more useful test than the C# nullability the inventory records: a C# `bool` or
 * `long` is non-nullable and still perfectly absent on the wire.
 *
 * **`long` is `number`, and for `messageId` that is currently WRONG — see below.** Never
 * `bigint`: `JSON.parse` cannot produce one, so a `bigint` field would be a lie the first time a
 * frame was decoded. `number` is exact to 2^53, and every seq and unix-ms timestamp this
 * platform issues does stay well inside it.
 *
 * **`messageId` does not.** Measured against a live server on 2026-08-25: the server issued
 * `350598345233801216`, about 2^58 — thirty-eight times past the safe limit. Calling
 * `msg.recall` with the value a JS client sends back returns 1400 `message not found`; the
 * same call with the exact id succeeds.
 *
 * **The mechanism is not what it first looks like, and the difference matters.** Doubles near
 * 2^58 are spaced 64 apart. That particular id has zero sequence bits, so it is a multiple of
 * 4096 and `JSON.parse` reproduces it *exactly* — `BigInt(parsed)` is the original. What is
 * lossy is the way back out: JavaScript prints a number as the shortest decimal that
 * round-trips to the same double, and for this value that shortest decimal is
 * `350598345233801200` — a different integer. So `JSON.stringify` sends the server an id it
 * never issued. An id minted with non-zero sequence bits is not a multiple of 64 at all and
 * is rounded on the way *in* instead (…223 arrives as …216).
 *
 * Either way a JavaScript client cannot round-trip a message id, which is why re-reading the
 * raw text on receive is not a sufficient fix: the value has to leave as a string too.
 * **这个机制和它初看的样子不一样**：2^58 附近相邻 double 相距 64，而该 id 序列位为 0、
 * 是 4096 的倍数，所以 JSON.parse 得到的是**精确值**；丢失发生在**回程**——
 * JS 打印数字用「能往返到同一个 double 的最短十进制」，于是写出 …200 这个**另一个整数**。
 * 序列位非 0 的 id 则在**来路**就被舍入。两种情形都无法完整往返。
 *
 * **It is not a future risk; it has been true since 2024-01-25.** The snowflake epoch is
 * 2024-01-01 and the timestamp is shifted left 22 bits, so an id stays under 2^53 only for the
 * first 24.86 days after that epoch. Every message id minted after 2024-01-25T20:31:23Z is
 * unsafe here, and the margin only grows.
 *
 * **Affected fields**: `messageId`, `quoteMessageId`, `threadRootId` and the `messageIds` array
 * on translation — all of them message ids, so quoted replies and threads are affected too.
 * `seq`, `minSeq`, `maxSeq` and `readSeq` are per-conversation counters and are safe.
 * 不是"将来会溢出"：epoch 是 2024-01-01、时间戳左移 22 位，安全窗口只有 24.86 天，
 * **2024-01-25 之后铸出的每一个消息 id 都不安全**。受影响的是全部消息 id 字段
 * （含 quoteMessageId / threadRootId / messageIds），seq 一族是会话内计数器、安全。
 * Every call that hands a messageId back is affected: recall, edit, delete, read receipts,
 * quoted replies, and translation's `messageIds`. `asLong()` does not help — it returns a
 * number input unchanged, and by then the precision is already gone.
 *
 * The sentence that used to stand here said all three id kinds stayed well inside 2^53. It was
 * wrong about messageId, and it is left retracted rather than deleted because anyone who read
 * it and sized a field on it needs to find it again. `groupId` is sent as a string and is fine;
 * that inconsistency inside one protocol is the actual bug. Fixing it changes the wire format
 * for five SDKs, so it is a product decision, not a patch — tracked as B-9.
 * 上面那句「messageId 稳稳在 2^53 以内」是**假的**：实测约 2^58，超出 38 倍，
 * JSON.parse 会静默取整，用取整后的值撤回会得到 1400，用精确值则成功。
 * groupId 是字符串、没有问题——**同一份协议里两种做法**，这才是真正的缺陷。
 *
 * 可选就是可选：服务端写 JSON 时省略 null，缺字段即默认值。只有端点会因为缺它而拒绝请求的字段
 * 才是必填——这比照搬 C# 可空性更有用，C# 的 bool/long 不可空，但在线上完全可以不出现。
 */

import type {
  ApplicationStatus,
  ConversationType,
  GroupInviteMode,
  GroupJoinMode,
  GroupRole,
  GroupType,
  MessageContentType,
  MessagePriority,
  MessageStatus,
  MultiLoginPolicy,
  MuteMode,
  Platform,
} from './protocol.js';

/**
 * `content` and `extensions` are per-`contentType` and tenant-extensible, so they stay untyped
 * JSON. Inventing a model for `content` would be wrong for the tenant that adds a field to it the
 * day after the SDK ships (CONTRACT §4.5).
 */
export type JsonObject = Record<string, unknown>;

// ---------------------------------------------------------------------------- conn (T0)

export interface HeartbeatResult {
  serverTime: number;
  /** How often to beat, in seconds. The server owns this cadence; the SDK adopts whatever it says. */
  intervalSeconds: number;
  /** True when this beat rebuilt a routing entry the cluster had lost. Worth logging, never acting on. */
  healed: boolean;
  /** This socket's cluster-unique id. Put it in a support ticket and the connection is findable. */
  connectionId: string;
  nodeId: string;
}

export interface ReauthRequest {
  token: string;
}

export interface ResumeRequest {
  /**
   * Highest **committed** seq per conversation — the seq the application has durably stored, not
   * the highest it has been handed. Reporting the latter is the data-loss bug in CONTRACT §5.1.
   */
  convSeqs?: Record<string, number>;
  /** Newest `ConversationView.updatedAt` fully consumed, unix ms. */
  conversationCursor?: number;
  cursor?: string | null;
  /** Server clamps to 1…500; anything outside becomes 200. */
  limit?: number;
}

export interface ResumeResult {
  conversations: ConversationView[];
  nextCursor?: string | null;
  hasMore: boolean;
  /** conversationId → first seq the client is missing. Feed each into `msg.sync`. */
  gapsFrom: Record<string, number>;
  serverTime: number;
}

// ---------------------------------------------------------------------------- messages

export interface RecallInfo {
  operatorId: string;
  recallTime: number;
  byAdmin: boolean;
  reason?: string | null;
}

export interface EditInfo {
  operatorId: string;
  editTime: number;
  version: number;
}

export interface PushConfig {
  title?: string | null;
  body?: string | null;
  sound?: string | null;
  payload?: Record<string, string> | null;
  badgeCount?: boolean;
  channelId?: string | null;
}

export interface MessageOptions {
  persistent?: boolean;
  updateConversation?: boolean;
  countUnread?: boolean;
  offlinePush?: boolean;
  pushConfig?: PushConfig | null;
  needReceipt?: boolean;
  priority?: MessagePriority;
  /** Online-only messages carry `seq: 0` and never touch a cursor. */
  onlineOnly?: boolean;
  noSelfSync?: boolean;
  expireIn?: number | null;
  moderationBypass?: boolean;
}

export interface ImMessage {
  appId: string;
  conversationId: string;
  conversationType: ConversationType;
  /**
   * Gap-free position inside the conversation. Ordering, dedupe and gap repair all key off this.
   * `0` means the message was never persisted (typing, presence, chat-room traffic).
   */
  seq: number;
  messageId: string;
  clientMsgId: string;
  senderId: string;
  senderPlatform: Platform;
  contentType: MessageContentType;
  content: JsonObject;
  searchText?: string | null;
  mentionAll?: boolean;
  mentionedUserIds?: string[];
  quoteMessageId?: string | null;
  threadRootId?: string | null;
  options?: MessageOptions;
  status?: MessageStatus;
  recalled?: RecallInfo | null;
  edited?: EditInfo | null;
  reactions?: Record<string, string[]> | null;
  deletedForUsers?: string[] | null;
  sendTime: number;
  /** Authoritative server clock, unix ms. */
  createTime: number;
  expireAt?: number | null;
  extensions?: JsonObject | null;
}

export interface MessageBrief {
  messageId: string;
  seq: number;
  senderId: string;
  contentType: MessageContentType;
  digest: string;
  createTime: number;
  recalled: boolean;
}

export interface SendMessageRequest {
  /** One of `conversationId`, `receiverId` or `groupId`. The server resolves the other two. */
  conversationId?: string;
  receiverId?: string;
  groupId?: string;
  conversationType?: ConversationType;
  /**
   * Idempotency key. Optional here because the SDK generates one when it is absent — which is what
   * makes a blind retry safe for a caller who never thought about it.
   */
  clientMsgId?: string;
  /** Defaults to `MessageContentType.Text`. */
  contentType?: MessageContentType;
  content: JsonObject;
  mentionAll?: boolean;
  mentionedUserIds?: string[];
  quoteMessageId?: string;
  threadRootId?: string;
  options?: MessageOptions;
  /** Client clock, unix ms. The SDK fills it in; the server does not trust it for ordering. */
  sendTime?: number;
  extensions?: JsonObject;
}

export interface SendMessageResult {
  messageId: string;
  seq: number;
  conversationId: string;
  clientMsgId: string;
  createTime: number;
  /** True when the server matched an earlier send on `clientMsgId` and returned the original result. */
  deduplicated?: boolean;
  contentModified?: boolean;
}

export interface SyncMessagesRequest {
  conversationId: string;
  fromSeq?: number;
  /** 0 means "up to the conversation's maxSeq". */
  toSeq?: number;
  /** Server clamps to 500. A wider window is more iterations of the repair loop, not a bigger call. */
  limit?: number;
  ascending?: boolean;
}

export interface SyncMessagesResult {
  conversationId: string;
  messages: ImMessage[];
  maxSeq: number;
  /** Lowest seq this user may read — a cleared history or a late group join raises it. */
  minSeq: number;
  /**
   * Computed on the raw window, **before** per-user hidden messages are filtered out. So
   * `messages` can be shorter than `limit` — even empty — while this is true. Loop on this, never
   * on `messages.length` (CONTRACT §5.9).
   */
  hasMore: boolean;
}

export interface HistoryRequest {
  conversationId: string;
  /** Exclusive: the oldest seq you already hold. Omit for the newest page. */
  beforeSeq?: number;
  /** Server clamps to 200; defaults to 20. */
  limit?: number;
}

export interface RecallMessageRequest {
  conversationId: string;
  messageId: string;
  reason?: string;
}

export interface DeleteMessagesRequest {
  conversationId: string;
  messageIds: string[];
  /** Deleting for everyone needs the permission the server checks; it is not a client capability by default. */
  forEveryone?: boolean;
}

export interface EditMessageRequest {
  conversationId: string;
  messageId: string;
  content: JsonObject;
}

export interface ForwardMessagesRequest {
  sourceConversationId: string;
  messageIds: string[];
  targetConversationIds: string[];
  /** True bundles them into one merged message rather than forwarding each. */
  merge?: boolean;
  mergeTitle?: string;
  clientMsgId?: string;
}

export interface ReactRequest {
  conversationId: string;
  messageId: string;
  emoji: string;
  /** False removes the caller's reaction. Defaults to true. */
  add?: boolean;
}

export interface ReceiptRequest {
  conversationId: string;
  messageIds: string[];
}

export interface TypingRequest {
  conversationId: string;
  typing?: boolean;
}

// ---------------------------------------------------------------------------- conversations

export interface ConversationSetting {
  pinned?: boolean;
  muted?: MuteMode;
  draft?: string;
  tags?: string[];
  extensions?: JsonObject;
}

export interface ConversationView {
  conversationId: string;
  type: ConversationType;
  lastMessage?: MessageBrief | null;
  maxSeq: number;
  readSeq: number;
  unreadCount: number;
  pinned: boolean;
  muted: MuteMode;
  draft?: string | null;
  tags?: string[] | null;
  manuallyUnread?: boolean;
  /** Sort key of the conversation list and the input to `conversationCursor`. Unix ms. */
  updatedAt: number;
  /** Present for single conversations when the server can resolve the peer cheaply. */
  peer?: UserProfile | null;
  group?: Group | null;
  extensions?: JsonObject | null;
}

export interface ListConversationsRequest {
  /** Only conversations changed after this unix-ms timestamp. 0 means all. */
  updatedAfter?: number;
  cursor?: string | null;
  /** Server clamps to 200; defaults to 50. */
  limit?: number;
}

export interface ConversationIdRequest {
  conversationId: string;
}

export interface ReadRequest {
  conversationId: string;
  readSeq: number;
}

export interface UpdateConversationSettingRequest {
  conversationId: string;
  setting?: ConversationSetting;
}

// ---------------------------------------------------------------------------- users

export interface UserProfile {
  appId: string;
  userId: string;
  nickname?: string | null;
  avatar?: string | null;
  gender?: number;
  birthday?: string | null;
  signature?: string | null;
  /** Hashed server-side; the plaintext never reaches a client. */
  phoneHash?: string | null;
  emailHash?: string | null;
  silencedUntil?: number | null;
  banned?: boolean;
  multiLoginOverride?: MultiLoginPolicy | null;
  createdAt: number;
  updatedAt: number;
  extensions?: JsonObject | null;
}

export interface UserIdRequest {
  userId: string;
}

export interface UserIdsRequest {
  /** At most 200 per request; the server refuses more rather than truncating silently. */
  userIds: string[];
}

export interface UpdateProfileRequest {
  /**
   * Sparse patch. `appId`, `userId`, `banned`, `silencedUntil`, `createdAt` and
   * `multiLoginOverride` are stripped server-side whatever the client sends — a client must never
   * be able to unban itself.
   */
  patch: JsonObject;
}

export interface PresenceState {
  userId: string;
  online: boolean;
  platforms: Platform[];
  lastSeen: number;
  customStatus?: string | null;
}

export interface SubscribePresenceRequest {
  userIds: string[];
  /**
   * Subscriptions expire rather than living until an unsubscribe, because a client that crashes
   * never sends one. 1…3600; anything outside becomes 600.
   */
  ttlSeconds?: number;
}

// ---------------------------------------------------------------------------- friends

export interface Friend {
  appId: string;
  userId: string;
  friendUserId: string;
  remark?: string | null;
  tags?: string[] | null;
  source?: string | null;
  addTime: number;
  extensions?: JsonObject | null;
}

export interface FriendRequest {
  appId: string;
  fromUserId: string;
  toUserId: string;
  greeting?: string | null;
  source?: string | null;
  status: ApplicationStatus;
  handleReason?: string | null;
  createdAt: number;
  handledAt?: number | null;
}

export interface BlockEntry {
  appId: string;
  userId: string;
  blockedUserId: string;
  createdAt: number;
  reason?: string | null;
}

export interface CursorRequest {
  cursor?: string | null;
  /** 1…200; anything outside becomes 50. */
  limit?: number;
}

export interface AddFriendRequest {
  userId: string;
  greeting?: string;
  source?: string;
}

export interface HandleFriendRequest {
  fromUserId: string;
  accept: boolean;
  reason?: string;
}

export interface FriendRequestListRequest {
  /** True lists requests sent to me; false lists requests I sent. Defaults to true. */
  incoming?: boolean;
  cursor?: string | null;
  limit?: number;
}

export interface BlockRequest {
  userId: string;
  reason?: string;
}

// ---------------------------------------------------------------------------- groups

export interface Group {
  appId: string;
  groupId: string;
  type: GroupType;
  name: string;
  avatar?: string | null;
  introduction?: string | null;
  announcement?: string | null;
  announcementUpdatedAt?: number | null;
  ownerId: string;
  memberCount: number;
  maxMemberCount: number;
  joinMode: GroupJoinMode;
  inviteMode: GroupInviteMode;
  muteAll: boolean;
  muteEndTime?: number | null;
  dismissed: boolean;
  createdAt: number;
  updatedAt: number;
  extensions?: JsonObject | null;
}

export interface GroupMember {
  appId: string;
  groupId: string;
  userId: string;
  role: GroupRole;
  nickname?: string | null;
  muteEndTime?: number | null;
  joinTime: number;
  joinSource?: string | null;
  extensions?: JsonObject | null;
}

export interface CreateGroupRequest {
  /** Leave empty and the server allocates one. */
  groupId?: string;
  name: string;
  avatar?: string;
  introduction?: string;
  type?: GroupType;
  /** The caller is added and made owner whatever this says. */
  memberIds?: string[];
  joinMode?: GroupJoinMode;
  inviteMode?: GroupInviteMode;
  maxMemberCount?: number;
  extensions?: JsonObject;
}

export interface GroupIdRequest {
  groupId: string;
}

export interface UpdateGroupRequest {
  name?: string;
  avatar?: string;
  introduction?: string;
  joinMode?: GroupJoinMode;
  inviteMode?: GroupInviteMode;
  maxMemberCount?: number;
  extensions?: JsonObject;
}

export interface UpdateGroupCommand {
  groupId: string;
  update?: UpdateGroupRequest;
}

export interface GroupCursorRequest {
  groupId: string;
  cursor?: string | null;
  /** 1…100; anything outside becomes 50. A super group is never listed in one frame. */
  limit?: number;
}

export interface GroupMembersRequest {
  groupId: string;
  userIds: string[];
  reason?: string;
}

export interface JoinGroupRequest {
  groupId: string;
  reason?: string;
}

// ---------------------------------------------------------------------------- media

export interface UploadTicketRequest {
  fileName: string;
  /** MIME type. The server refuses types the tenant has not allowed rather than accepting the upload. */
  contentType: string;
  size?: number;
}

export interface MediaUploadTicket {
  /**
   * Put **this** in the message, never `downloadUrl`. Every reader signs their own short-lived
   * link from the key, which is what makes expiry and revocation possible at all — a URL baked
   * into a message is public forever the moment it leaks.
   */
  objectKey: string;
  /** Presigned PUT. Upload goes straight to object storage, never through the gateway. */
  uploadUrl: string;
  downloadUrl: string;
  /** Present when the storage backend needs a multipart POST rather than a PUT. */
  formFields?: Record<string, string> | null;
  expiresAt: number;
}

export interface DownloadUrlRequest {
  objectKey: string;
  /** 1…86400; anything outside becomes 3600. */
  lifetimeSeconds?: number;
}

// ---------------------------------------------------------------------------- push

/**
 * Vendor channel. Aliases (`ios`, `firebase`, `hms`, …) are folded server-side; an unknown value is
 * **rejected** with the legal list rather than stored as a token nothing can route.
 *
 * Empty falls back to the platform default, which is only reliable on iOS — Android fragments
 * across five OEM channels and the server cannot guess which one a token came from (CONTRACT §6.1).
 */
export type PushProvider = 'apns' | 'fcm' | 'huawei' | 'xiaomi' | 'oppo' | 'vivo' | 'honor' | (string & {});

export interface RegisterPushTokenRequest {
  provider: PushProvider;
  token: string;
  /** BCP-47. Defaults to the socket's `lang`. */
  language?: string;
}

/**
 * Body of `push.clicked` — the tap on a notification, reported back for the delivery funnel.
 *
 * **Both fields are optional and the identity is never in the body.** The row is located from the
 * connection: a `pushId` is only believed when it points at this user's own device, and without one
 * the server takes this device's newest delivery. That is what stops a client from marking another
 * user's notification clicked, or probing which `pushId` values exist.
 *
 * `messageId` is a **string** for the reason every message id in this SDK is one: the ids exceed
 * JavaScript's exact-integer range, and a number round-trips to a different id.
 */
export interface PushClickedRequest {
  /** The delivery's `pu_…` id, when the notification payload carried one. */
  pushId?: string;
  /** The payload's `msgId`, when the tap gave you one. */
  messageId?: string;
}
